Feature/for early adopter
AstarNetwork/crowdloan-app pull request #55
Opened 2021-12-20 03:05 UTC by sirius651

![스크린샷 2021-12-20 오전 11 30 47](https://user-images.githubusercontent.com/1606820/146704498-ed0ff901-a110-4b07-bda9-f20a6c44506e.png)

Choose account when displaying the amount of contributed => Connect metamask for eth account which participated in the previous lockdrop => Checking if the address is valid for bonus reward based on lockdrop history 1,2 => Store the data to FB db

2021-12-20 03:15 UTC, sirius651 commented
@hoonsubin can you please check this? but did we already calculate early adopter bonus without connecting ecdsa account?

2021-12-20 08:19 UTC, hoonsubin commented
@sirius651 Yes, we calculated the ECDSA account bonus too, but we still did not do accounts that use hardware wallets or who used a different address to participate in the crowdloan.

2021-12-20 11:29 UTC, hoonsubin requested changes
There are also some changes we need to make regarding the reward eligibility check itself and the data source, but that will require additional investigation from my side. First, please focus on these changes.

2021-12-20 11:29 UTC, hoonsubin commented on src/components/earlyadopter/ConnectAccount.vue
> +                <AccountOption
![Screen Shot 2021-12-20 at 12 10 41 PM](https://user-images.githubusercontent.com/40356749/146758435-57474e4a-8585-43a4-9b31-6b1adfac3852.png)
The properties should be in a straight line (the position of the 'DOT' text)

2021-12-20 11:29 UTC, hoonsubin commented on src/components/earlyadopter/ConnectAccount.vue
> +                    You deserve a bonus:
The text should say,
`This account is eligible for a early bird bonus`

And the other text should say,
`This account did not participate in the Lockdrop` (we assume that all the polkadot accounts displayed on the page have participated in the polkadot crowdloan).

2021-12-20 11:29 UTC, hoonsubin commented on src/router/index.ts
> +    path: '/early-adopter',
There should be a button on the mast head that leads to this page

2021-12-20 11:29 UTC, hoonsubin commented on src/components/earlyadopter/ConnectAccount.vue
> +      const firstCrowdloan = await response.json();
The name `firstCrowdloan` might be confusing here because we are talking about `lockdrop` events

2021-12-20 11:29 UTC, hoonsubin commented on src/components/earlyadopter/ConnectAccount.vue
> +                  v-for="(account, index) in allAccounts"
I think this should only display accounts that have participated in the crowdloan, not all accounts from the wallet.
If there are no accounts to display, say `You did not participated in the Polkadot Crowdloan`

2021-12-22 07:32 UTC, sirius651 commented
@hoonsubin Resolved above issue, could you review on that. and do we need show leaderboard in main page once the reward calculation done?

2021-12-22 18:59 UTC, hoonsubin approved these changes
LGTM

2021-12-22 19:00 UTC, hoonsubin commented
@sirius651 Yes, I think showing it in the main page is important

2021-12-22 19:13 UTC, hoonsubin requested changes
Sorry, my previous review was wrong

2021-12-22 19:13 UTC, hoonsubin commented on src/components/earlyadopter/ConnectAccount.vue
> +      isResultReward.value = true;
Is this value ever mutated?

2021-12-22 19:13 UTC, hoonsubin commented on src/components/earlyadopter/ConnectAccount.vue
> +                  <div v-if="prevLockdropInfo">
My address `0x01734005354d569716291cD1CFbc67f3f56a0b6F` participated in the first lockdrop, but the page says that I did not participate in it.
![bandicam 2021-12-22 20-10-14-098](https://user-images.githubusercontent.com/40356749/147143252-b555a53e-60a8-4fc0-a27f-18657a45d2d0.jpg)

Furthermore, if the user is eligible for the lockdrop bonus, there should be a button to apply the bonus where clicking the button will send the user's Ethereum address and Polkadot address that was used to contribute to the crowdloan. This information should be saved to the database and later exported for our reward calculation.
The early bird UI will check if the Ethereum address is already submitted or not (prevent double submission).

2021-12-22 19:50 UTC, hoonsubin commented
I have a new design proposal. Right now, we load the account and request the ECDSA signature. But instead of that, what about we
1. request connection to MetaMask
2. check if the account participated in the lockdrop
3. show the Polkadot.js account list if the account did participate in the lockdrop

So the UI should look like this:

![check-lockdrop](https://user-images.githubusercontent.com/40356749/147147241-4164c525-5a88-4a1b-8750-7557aa123794.jpg)
If the user clicks the button, request a connection to MetaMask and check if the account participated in the lockdrop or if the account bonus was already applied or not.

![apply-bonus](https://user-images.githubusercontent.com/40356749/147147318-df0d43c9-a313-415a-a930-e5e9a9d8c552.jpg)
Let the user select a Polkadot account that participated in the Crowdloan. It can display the expected bonus amount and clicking the 'Apply' button should send the Ethereum address, SS58 address that was encoded from the ECDSA public key, and the selected Polkadot address that the user wishes to apply the bonus.

What do you think?

2021-12-23 06:53 UTC, sirius651 commented
> What do you think?

cool that's more makes sense, I'll change right away

2021-12-24 13:01 UTC, sirius651 commented
@hoonsubin changed process based on above. can you check that what we expected?

2021-12-24 13:04 UTC, hoonsubin commented
@sirius651 the user flow is correct, Great job!

But I still get the `This account did not participate in the Lockdrop` message from my Ethereum account that participated in the lockdrop. Can you find out what may be the cause?

![Screen Shot 2021-12-24 at 2 04 00 PM](https://user-images.githubusercontent.com/40356749/147354725-8db9735d-cab5-4230-a1a3-1e8b492f19d0.png)
Note: the Ethereum account participated in the lockdrop while the Dot account did not participate in the Crowdloan

2021-12-25 02:30 UTC, sirius651 commented
> @sirius651 the user flow is correct, Great job!
> 
> But I still get the `This account did not participate in the Lockdrop` message from my Ethereum account that participated in the lockdrop. Can you find out what may be the cause?
> 
> ![Screen Shot 2021-12-24 at 2 04 00 PM](https://user-images.githubusercontent.com/40356749/147354725-8db9735d-cab5-4230-a1a3-1e8b492f19d0.png) Note: my Ethereum account participated in the lockdrop while the Dot account did not participate in the Crowdloan

@hoonsubin is your address `0x01734005354d569716291cD1CFbc67f3f56a0b6F` right? when I test the function with that address it seems works well. can you check like this console log?
<img width="1138" alt="스크린샷 2021-12-25 오전 11 28 31" src="https://user-images.githubusercontent.com/1606820/147376133-7b81d83a-bd99-4d90-825f-9fcb361f3073.png">

2021-12-25 15:46 UTC, hoonsubin commented
![bandicam 2021-12-25 16-45-28-830](https://user-images.githubusercontent.com/40356749/147388602-672bde1c-a9a5-47d6-8cbc-7d1f9fecc2a1.jpg)

Sorry for the late response, here is my log. The address you pasted is correct.

2021-12-26 06:17 UTC, sirius651 commented
> Sorry for the late response, here is my log. The address you pasted is correct.

hmm I think that's weird. but the only difference is that`Failed to load resource: ERR_BLOCKED_BY_CLIENT`. maybe something(like json file) is not loaded on your end because of some reason?

2021-12-26 10:44 UTC, hoonsubin commented
![bandicam 2021-12-26 11-43-57-087](https://user-images.githubusercontent.com/40356749/147405736-dadaddd7-b20b-42a9-b719-c67179de517a.jpg)
I thought so too, but if I look at the network debug, the json file is loaded.

2021-12-27 11:54 UTC, sirius651 commented
> I thought so too, but if I look at the network debug, the json file is loaded.

oh I found the issue. I missed convert `lockOwner` to lowercase letters. Could you check again & the data is stored on `bonus-user` in `crowdloan-app-cef78` at FB

2021-12-27 13:10 UTC, hoonsubin commented
Finally, it works!
Just one last problem, the page doesn't seem to load all the accounts on my Polkadot wallet.
![bandicam 2021-12-27 14-09-41-305](https://user-images.githubusercontent.com/40356749/147474878-afb459f0-a5a3-45ba-b0ac-61c58de2cf9c.jpg)

Do you know what the cause is?

2021-12-28 01:32 UTC, sirius651 commented
> Do you know what the cause is?

because based on this https://github.com/AstarNetwork/crowdloan-app/pull/55#issuecomment-999824118
it only shows the account which already contributed to crowdloan. https://github.com/AstarNetwork/crowdloan-app/pull/55/files#diff-712d2cef88e4a8dbc9131c13489bd76a24132ffeb8f67e1de9f844ed6459e0a2R159

2022-01-03 11:38 UTC, hoonsubin commented
> 

Sorry for the late response. The problem is that the first account you see on the above screenshot did not participate in the crowdloan. So the page should show a message like 'you did not participate in the crowdloan'

2022-01-03 15:45 UTC, hoonsubin commented
@sirius651 I found the issue. So the account `1j5YyEGdcPd9BxkzVNNjKkqdi5f7g3Dd7JMgaGUhsMrZ6dZ` did participate in the auction, however, I saved that account as `Stake Technologies` in my wallet. The `Hoon ECDSA` account is the first account in the wallet and did not participate in the crowdloan.
In other words, the UI is reading the name of the wallet with the index 0 while getting the correct address for a different account.

2022-01-04 05:20 UTC, sirius651 commented
> @sirius651 I found the issue. So the account `1j5YyEGdcPd9BxkzVNNjKkqdi5f7g3Dd7JMgaGUhsMrZ6dZ` did participate in the auction, however, I saved that account as `Stake Technologies` in my wallet. The `Hoon ECDSA` account is the first account in the wallet and did not participate in the crowdloan.
> In other words, the UI is reading the name of the wallet with the index 0 while getting the correct address for a different account (as you can see from the screenshot)

oh yes, you're right. appreciate it. fixed now.

2022-01-04 06:48 UTC, hoonsubin approved these changes
LGTM

2022-01-04 06:49 UTC, merged